"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { motion } from "framer-motion";
import { Loader2, Store, Users, Eye, Calendar } from "lucide-react";

export default function ShowcasePage() {
  const [storefronts, setStorefronts] = useState([]);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    const fetchStorefronts = async () => {
      try {
        const response = await fetch("/api/store");
        if (!response.ok) throw new Error("Failed to fetch showcase");
        const data = await response.json();
        setStorefronts(data);
      } catch (error) {
        console.error("Error loading showcase:", error);
      } finally {
        setIsLoading(false);
      }
    };

    fetchStorefronts();
  }, []);

  if (isLoading) {
    return (
      <div className="min-h-screen bg-[#080408] flexflex-col items-center justify-center p-6 text-white text-center space-y-6">
        <Loader2 className="animate-spin w-16 h-16 text-[#00E5FF] mx-auto" strokeWidth={1} />
        <p className="text-[#ffffff99] tracking-widest uppercase text-sm font-bold">Loading The Matrix...</p>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-[#080408] text-white pt-32 pb-20 px-6 font-sans selection:bg-[#00e5ff4d] selection:text-white relative overflow-hidden">
      {/* Background Ambience */}
      <div className="absolute top-[-20%] left-[-10%] w-[50%] h-[50%] bg-[#00e5ff1a] rounded-full mix-blend-screen filter blur-[150px] opacity-70 animate-pulse-slow"></div>
      <div className="absolute bottom-[-20%] right-[-10%] w-[50%] h-[50%] bg-[#c0152a1a] rounded-full mix-blend-screen filter blur-[150px] opacity-70 animate-pulse-slow" style={{ animationDelay: "2s" }}></div>
      <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 mix-blend-overlay pointer-events-none"></div>

      <div className="max-w-7xl mx-auto relative z-10 space-y-16">
        <div className="text-center space-y-6">
          <motion.div initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.8, ease: "easeOut" }} className="inline-block px-6 py-2 rounded-full glass border border-[#ffffff1a] mb-4">
            <span className="bg-gradient-to-r from-[#00E5FF] to-[#C0152A] bg-clip-text text-transparent italic font-black text-sm uppercase tracking-widest">Global Gallery</span>
          </motion.div>
          <motion.h1 initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.1 }} className="text-5xl md:text-7xl font-black italic tracking-tighter uppercase leading-none">
            VibeShop{" "}
            <span className="text-transparent bg-clip-text" style={{ background: "linear-gradient(to right, #00E5FF, #ffffff)", WebkitBackgroundClip: "text" }}>
              Showcase
            </span>
          </motion.h1>
          <motion.p initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8, delay: 0.2 }} className="text-[#ffffff80] text-lg md:text-xl font-medium max-w-2xl mx-auto leading-relaxed">
            Explore the most aesthetic digital storefronts generated by our community using AI.
          </motion.p>
        </div>

        {storefronts.length === 0 ? (
          <div className="glass rounded-[3rem] p-16 text-center border border-[#ffffff0d]">
            <Store className="w-16 h-16 mx-auto text-[#ffffff33] mb-6" />
            <h3 className="text-2xl font-bold mb-2">No Storefronts Yet</h3>
            <p className="text-[#ffffff66]">Be the first to generate and publish a VibeShop.</p>
            <Link href="/" className="inline-block mt-8 bg-[#00E5FF] text-[#080408] px-8 py-4 rounded-full font-black uppercase tracking-widest text-sm hover:bg-white transition-colors">
              Create One Now
            </Link>
          </div>
        ) : (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {storefronts.map((store, index) => {
              const shopData = store.data || {};
              const products = shopData.products || [];
              const productCount = products.length;
              const targetImage = products.length > 0 ? products[0].image : null;

              return (
                <motion.div key={store.id} initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: index * 0.1 }}>
                  <Link href={`/preview/${store.slug}`}>
                    <div className="glass rounded-[2.5rem] overflow-hidden group border border-[#ffffff0d] hover:border-[#00e5ff4d] transition-all duration-500 shadow-2xl relative h-full flex flex-col cursor-pointer">
                      {/* Image Banner */}
                      <div className="h-48 overflow-hidden relative">
                        {targetImage ? (
                          <img
                            src={`/api/proxy-image?url=${encodeURIComponent(targetImage)}`}
                            alt={shopData.name}
                            className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-1000 scale-110 group-hover:scale-100"
                            crossOrigin="anonymous"
                          />
                        ) : (
                          <div className="w-full h-full bg-[#111]" />
                        )}
                        <div className="absolute inset-0 opacity-90 transition-opacity group-hover:opacity-70" style={{ background: "linear-gradient(to top, #080408, #08040866, transparent)" }} />
                        <div className="absolute top-4 right-4 glass px-4 py-1.5 rounded-full border border-[#ffffff1a] font-bold text-xs text-[#ffffff99] flex items-center gap-2 backdrop-blur-xl">
                          <Eye size={14} />
                          {store.views || 0}
                        </div>
                      </div>

                      {/* Content */}
                      <div className="p-8 flex-1 flex flex-col relative z-10 -mt-10">
                        <div className="glass-solid bg-[#080408] rounded-2xl p-6 border border-[#ffffff1a] flex-1 flex flex-col shadow-xl">
                          <h3 className="text-2xl font-black text-white italic tracking-tighter uppercase leading-tight group-hover:text-[#00E5FF] transition-colors duration-500 line-clamp-1 mb-2">{shopData.name || "Untitled Shop"}</h3>
                          <p className="text-[#ffffff66] text-sm font-medium leading-relaxed line-clamp-2 mb-6 flex-1">{shopData.description || "No description provided."}</p>

                          <div className="flex items-center justify-between text-xs text-[#ffffff4d] font-bold uppercase tracking-wider pt-4 border-t border-[#ffffff0d]">
                            <div className="flex items-center gap-2">
                              <Store size={14} />
                              <span>{productCount} Items</span>
                            </div>
                            <div className="flex items-center gap-2">
                              <Calendar size={14} />
                              <span>{new Date(store.created_at).toLocaleDateString()}</span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </Link>
                </motion.div>
              );
            })}
          </div>
        )}
      </div>

      {/* Footer Vibe */}
      <footer className="mt-20 py-12 text-center border-t border-[#ffffff0d] flex flex-col items-center gap-4">
        <div className="flex items-center gap-2 opacity-50 hover:opacity-100 transition-opacity">
          <img src="/logo.png" alt="Abyan Studio" className="w-6 h-6 rounded-md" />
          <span className="text-xs font-mono tracking-widest uppercase text-white/50">Built by Abyan Studio</span>
        </div>
        <p className="text-white/10 text-[10px] font-mono tracking-[0.3em] uppercase italic">VibeShop AI Showcase — Future Commerce</p>
      </footer>
    </div>
  );
}
